# This file is for running the application locally

services:

  web:
    image: gbif-se/website-dev
    build: 
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - CODESPACES
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/site
