services:

  web:
    image: bretfisher/jekyll-serve
    ports:
      - 4000:4000
      - 4001:4001
    volumes:
      - .:/site
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload --livereload-port 4001
