on:
  push:
    branches: [ build ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
      - run: bundle install 

      - run: jekyll build

#     - name: Build the site in the jekyll/builder container
#       run: |
#         docker run \
#         -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
#         jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
